name: Akhenaten Build Linux (Flatpak)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: run on linux
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: update-workspace
      run: |
        sudo apt -qq update
        sudo apt install --yes flatpak-builder
    - name: build-project
      run: |
        sudo flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
        sudo flatpak-builder repo com.github.dalerank.akhenaten.json --install-deps-from=flathub --keep-build-dirs
        flatpak build-export export repo
        flatpak build-bundle export akhenaten.flatpak com.github.dalerank.akhenaten --runtime-repo=https://flathub.org/repo/flathub.flatpakrepo
    - uses: actions/upload-artifact@v4
      with:
        name: akhenaten.flatpak
        path: akhenaten.flatpak
