name: Akhenaten Build Linux

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: run on linux
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: update-workspace
      run: |
        sudo apt -qq update
        sudo apt install --yes cmake build-essential libsdl2-dev libsdl2-mixer-dev libsdl2-image-dev
    - name: build-project
      run: |
        git submodule init && git submodule update ext/cpptrace
        mkdir build
        mkdir linux_build
        cd build
        cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
        cd ..
        cmake --build ./build
        cp ./build/akhenaten ./linux_build/akhenaten.linux
    - uses: actions/upload-artifact@v3
      with:
        name: linux_build
        path: linux_build