name: Akhenaten Build Mac

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: run on mac
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: update-workspace
      run: |
        brew install llvm@15
        whereis clang++
        export CC=/usr/local/opt/llvm@15/bin/clang
        export CXX=/usr/local/opt/llvm@15/bin/clang++
        export CXXFLAGS=-stdlib=libc++
        ./update-workspace-mac.sh
        git submodule init && git submodule update ext/cpptrace
        cd build
        cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
        cd ..
        cmake --build ./build -j6
        mkdir macos_build
        cp -R ./build/akhenaten.app ./macos_build/akhenaten.app
    - uses: actions/upload-artifact@v3
      with:
        name: macos_build
        path: macos_build
