name: Akhenaten Build Mac

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: run on mac
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4.2.2
      with:
        fetch-depth: 0
        submodules: true
    - name: update-workspace
      run: |
        whereis clang++
        export CXXFLAGS=-stdlib=libc++
        ./update-workspace-mac.sh
        cd build
        cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" ..
        cd ..
    - name: build
      run: |
        cmake --build ./build -j6
    - name: install-and-bundle
      run: |
        cmake --build ./build --target install/local
        mkdir macos_build
        cp -R ./build/akhenaten.app ./macos_build/akhenaten.app
    - uses: actions/upload-artifact@v4.5.0
      with:
        name: macos_build
        path: macos_build
