name: Akhenaten Build Emscripten

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: run on linux
    runs-on: ubuntu-22.04
    container: emscripten/emsdk:4.0.1
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: build-project
      run: |
        git config --global --add safe.directory "*"
        mkdir -p akhenaten-emscripten-module
        mkdir -p build
        cd build
        emcmake cmake ../ -DCMAKE_BUILD_PLATFORM=win_emscripten -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXE_LINKER_FLAGS="-sMODULARIZE -sALLOW_MEMORY_GROWTH -sENVIRONMENT=web -sEXPORTED_RUNTIME_METHODS=callMain -sEXPORT_ALL -sEXPORT_NAME=akhenatem" -DCMAKE_CXX_FLAGS="" && emmake make
        cd ..
        cp build/akhenaten.js akhenaten-emscripten-module/
        cp build/akhenaten.wasm akhenaten-emscripten-module/
    - uses: actions/upload-artifact@v4
      with:
        name: emscripten_build
        path: akhenaten-emscripten-module