name: Ozymandias Build Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  windows:
    name: run on windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ilammy/msvc-dev-cmd@v1.12.1
    - name: update-workspace
      shell: pwsh
      run: |
        git clone https://github.com/jeremy-rifkin/cpptrace.git ext/cpptrace
        mkdir build
    - name: build-project
      run: |
        cd build
        cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
        cd ..
        cmake --build ./build --target ozymandias --config RelWithDebInfo
        copy ./build/RelWithDebInfo/ozymandias.exe ./bin_x64/ozymandias.exe
    - name: create-package
      shell: pwsh
      run: |
        Compress-Archive -Path bin_x64/* -Destination windows_build.zip
    - uses: actions/upload-artifact@v3
      with:
        name: windows_build
        path: bin_x64