name: Ozymandias Build Content

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: run content
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: update-workspace
      run: |
        sudo apt -qq update
        sudo apt install --yes cmake build-essential libsdl2-dev libsdl2-mixer-dev libsdl2-image-dev unzip
    - name: build-project
      run: |
        git clone https://github.com/jeremy-rifkin/cpptrace.git etc/cpptrace
        mkdir build
        mkdir artifacts
        cd build
        cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
        cd ..
        cmake --build ./build
        wget https://nightly.link/dalerank/Ozymandias/workflows/ozymandias_windows/master/windows_build.zip
        cp ./build/ozymandias ./ozymandias.linux
        mv windows_build.zip all_platforms_build.zip
        zip -u -q "all_platforms_build.zip" "ozymandias.linux"
        current_date=$(date +"%Y_%m_%d")
        final_filename=all_platforms_build_${current_date}.zip
        echo "GITHUB_FINAL_FILENAME=${final_filename}" >> $GITHUB_ENV
        mv all_platforms_build.zip ${final_filename}
        unzip ${final_filename} -d artifacts
    - uses: actions/upload-artifact@v3
      with:
        name: linux_windows_build
        path: artifacts
    - uses: KikimoraGames/itch-publish@v0.0.3
      with:
        butlerApiKey: ${{ secrets.ITCHIO }}
        gameData: ${{ env.GITHUB_FINAL_FILENAME }}
        itchUsername: dalerank
        itchGameId: ozymandias
        buildChannel: linux-windows
