name: Ozymandias Build Matrix

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  windows:
    name: run on windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1.4.1
    - name: update-workspace
      run: |
        update-workspace.bat
        mkdir build
      shell: cmd
    - name: create-solution
      run: |
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release..
    - name: build-project
      run: |
        cmake --build ./build --target ozymandias --config Release